name: Testing git actions
on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        run: gh pr comment ${{ github.event.pull_request.html_url }} --body "Thanks for the PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 